### ISSUE TITLE
Idea: Move 'description' to metadata.yml (and switch from json -> yml for multiline value support) 

### ISSUE THREAD

**Issue by dciborow** [Azure/bicep-registry-modules#150]
Currently, the description must be set in the Readm.md, while the rest of the values are set in metadata.json. 

I wonder if this is because the description is expected to be multi-line, and that JSON has poor support for this. 

Current metadata.json

```json
{
  "$schema": "https://aka.ms/bicep-registry-module-metadata-file-schema-v2#",
  "name": "Azure Game Developer VMSS",
  "summary": "Bicep Module to simplify deployment of the Azure Game Developer VMSS",
  "owner": "dciborow"
}
```

Proposed metadata.yml
```yml
# yaml-language-server: $schema=https://aka.ms/bicep-registry-module-metadata-file-schema-v3
name: Azure Game Developer VMSS,
summary: Bicep Module to simplify deployment of the Azure Game Developer VMSS,
owner: dciborow
description: |
The Game Development Virtual Machine is a customizable development workstation or build server in Azure, pre-installed with common game development tooling for game creators to build their games in the cloud.
Microsoft partnered with the top game development partners to pre-install Visual Studio, Unreal Engine, Perforce Helix Core, Parsec, Teradici, Incredibuild, Blender, DirectX/GDK/PlayFab SDKs and more in a customizable Azure workstation to make deploying your game creation environment simple, seamless, and secure.
No additional costs are added above base Azure VM pricing for leveraging this VM, though Solutions like Incredibuild, Parsec and Teradici require you to Bring Your Own License (BYOL) when leveraging those products, and passing in licensing details is configurable on deployment.
The Game Development Virtual Machine currently supports Windows Server 2019 and Windows 10 operating systems.

See our [documentation](https://docs.microsoft.com/en-us/gaming/azure/game-dev-virtual-machine/) for more information.
```
